apiVersion: v1
kind: Service
metadata:
  name: expominio
spec:
  selector:
    io.kompose.service: minio
  ports:
  - protocol: "TCP"
  - name: "minio"
    port: 9000
    targetPort: 9000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
         app: minio
    spec:
      containers:
      - args:
        - server
        - minio2/export
        env:
        - name: MINIO_ACCESS_KEY
          value: daravuth
        - name: MINIO_SECRET_KEY
          value: daravuth
        image: minio/minio
        name: minio1
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
